import { getServerlessAuthToken } from './supabaseEntities';

// Mock Integration Functions with detailed logging
// Replace these with actual API calls to your backend services

interface LLMParams {
  prompt: string;
  model?: string;
  temperature?: number;
  max_tokens?: number;
}

interface LLMResponse {
  response: string;
  usage: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  model: string;
  finishReason: string;
}

interface EmailData {
  to: string | string[];
  subject: string;
  body: string;
  from?: string;
  cc?: string | string[];
  bcc?: string | string[];
  attachments?: any[];
}

interface EmailResponse {
  success: boolean;
  messageId: string;
  message: string;
  timestamp: string;
  recipients: string[];
}

interface BaseUploadParams {
  folder?: string;
  isPublic?: boolean;
  projectId?: string;
  dailyUpdateId?: string;
  phaseName?: string;
}

interface UploadFileParams extends BaseUploadParams {
  file: File;
}

interface UploadPhotosParams extends BaseUploadParams {
  files: File[];
}

export interface UploadedPhotoMetadata {
  bucket: string;
  path: string;
  folder: string;
  fileName: string;
  originalName: string;
  mimeType: string;
  size: number;
  uploadedAt: string;
  publicUrl: string | null;
  url: string | null;
  file_url: string | null;
}

interface UploadFileResponse extends UploadedPhotoMetadata {
  success: boolean;
  filename: string;
  type: string;
}

interface UploadApiResponse {
  success: boolean;
  bucket?: string;
  count?: number;
  uploads?: any[];
  error?: string;
  message?: string;
}

interface SMSData {
  to: string;
  message: string;
}

interface SMSResponse {
  success: boolean;
  messageId: string;
  to: string;
  status: string;
}

interface WebhookData {
  url: string;
  event: string;
  payload: any;
}

interface WebhookResponse {
  success: boolean;
  deliveredAt: string;
}

// AI/LLM Integration - for generating AI summaries, insights, etc.
export async function InvokeLLM(params: LLMParams): Promise<LLMResponse> {
  const { prompt, model, temperature, max_tokens } = params;
  
  console.log('%c[API CALL] InvokeLLM()', 'color: #E91E63; font-weight: bold');
  console.log('  → HTTP: POST /api/integrations/llm/invoke');
  console.log('  → Parameters:', {
    prompt: prompt?.substring(0, 100) + '...',
    model: model || 'gpt-4',
    temperature: temperature || 0.7,
    max_tokens: max_tokens || 1000
  });
  console.log('  → Expected backend action:');
  console.log('    1. Receive prompt and configuration');
  console.log('    2. Call OpenAI/Anthropic/etc API');
  console.log('    3. Return AI-generated response');
  console.log('    4. Optionally log usage/cost for billing');
  
  // Mock response - replace with actual LLM API call
  const mockResponse = {
    response: 'This is a mock AI response. In production, this would be generated by an LLM like GPT-4, Claude, or similar. The response would be based on the prompt provided.',
    usage: {
      promptTokens: prompt?.length ? Math.floor(prompt.length / 4) : 100,
      completionTokens: 50,
      totalTokens: 150,
    },
    model: model || 'gpt-4',
    finishReason: 'stop'
  };
  
  console.log('  ← Response tokens:', mockResponse.usage.totalTokens);
  return mockResponse;
}

// Email Service Integration
export async function SendEmail(emailData: EmailData): Promise<EmailResponse> {
  const { to, subject, body, from, attachments } = emailData;
  
  console.log('%c[API CALL] SendEmail()', 'color: #009688; font-weight: bold');
  console.log('  → HTTP: POST /api/integrations/email/send');
  console.log('  → Email details:', {
    to: Array.isArray(to) ? to.join(', ') : to,
    subject,
    from: from || 'noreply@rooftracker.com',
    bodyLength: body?.length || 0,
    hasAttachments: attachments && attachments.length > 0
  });
  console.log('  → Expected backend action:');
  console.log('    1. Validate email addresses');
  console.log('    2. Format email with template');
  console.log('    3. Send via SMTP/SendGrid/AWS SES/etc');
  console.log('    4. Handle bounces and track delivery');
  console.log('    5. Log email for audit trail');
  
  // Mock email sending
  const mockResponse = {
    success: true,
    messageId: `mock-${Date.now()}-${Math.random().toString(36).substring(7)}`,
    message: 'Email sent successfully (MOCK - not actually sent)',
    timestamp: new Date().toISOString(),
    recipients: Array.isArray(to) ? to : [to],
  };
  
  console.log('  ← Email "sent" with ID:', mockResponse.messageId);
  console.warn('  ⚠️  WARNING: This is a MOCK - no actual email was sent!');
  
  return mockResponse;
}

const DEFAULT_UPLOAD_FOLDER = 'uploads';
const UPLOAD_ENDPOINT = '/api/integrations/storage/upload';

const normalizeUploadMetadata = (
  upload: any,
  fallbackBucket: string,
  fallbackFolder?: string
): UploadedPhotoMetadata => {
  const bucket = upload?.bucket || fallbackBucket || '';
  const folder = upload?.folder || fallbackFolder || DEFAULT_UPLOAD_FOLDER;
  const fileName =
    upload?.fileName ||
    upload?.filename ||
    upload?.name ||
    `file-${Date.now().toString(36)}`;
  const originalName =
    upload?.originalName || upload?.originalFilename || upload?.name || fileName;
  const mimeType = upload?.mimeType || upload?.type || 'application/octet-stream';
  const size = Number(upload?.size) || 0;
  const uploadedAt = upload?.uploadedAt || new Date().toISOString();
  const path = upload?.path || `${folder}/${fileName}`;
  const publicUrl = upload?.publicUrl || upload?.url || upload?.file_url || null;

  return {
    bucket,
    path,
    folder,
    fileName,
    originalName,
    mimeType,
    size,
    uploadedAt,
    publicUrl,
    url: publicUrl,
    file_url: publicUrl,
  };
};

export async function UploadPhotos(params: UploadPhotosParams): Promise<UploadedPhotoMetadata[]> {
  const { files, folder, isPublic, projectId, dailyUpdateId, phaseName } = params;

  if (!files || files.length === 0) {
    throw new Error('No files provided for upload');
  }

  console.log('%c[API CALL] UploadPhotos()', 'color: #FF9800; font-weight: bold');
  console.log('  → HTTP: POST /api/integrations/storage/upload');
  console.log('  → Files:', files.map((file) => `${file.name} (${(file.size / 1024).toFixed(1)} KB)`));

  const token = await getServerlessAuthToken();
  const formData = new FormData();

  files.forEach((file) => formData.append('photos', file));

  if (folder) {
    formData.append('folder', folder);
  }
  if (projectId) {
    formData.append('project_id', projectId);
  }
  if (phaseName) {
    formData.append('phase_name', phaseName);
  }
  if (dailyUpdateId) {
    formData.append('daily_update_id', dailyUpdateId);
  }
  if (typeof isPublic === 'boolean') {
    formData.append('isPublic', String(isPublic));
  }

  const response = await fetch(UPLOAD_ENDPOINT, {
    method: 'POST',
    headers: {
      Authorization: token,
    },
    credentials: 'include',
    body: formData,
  });

  const contentType = response.headers.get('content-type') || '';
  if (!contentType.includes('application/json')) {
    const responseText = await response.text();
    throw new Error(`Unexpected response type: ${contentType || 'unknown'} - ${responseText}`);
  }

  const payload = (await response.json()) as UploadApiResponse;
  if (!response.ok) {
    const message = payload?.message || payload?.error || 'File upload failed';
    throw new Error(message);
  }

  const uploads = Array.isArray(payload?.uploads) ? payload.uploads : [];
  if (uploads.length === 0) {
    throw new Error('Upload completed but no files were returned from the server');
  }

  const normalizedUploads = uploads.map((upload) =>
    normalizeUploadMetadata(upload, payload?.bucket || '', folder)
  );

  console.log('  ← Uploaded files:', normalizedUploads.length);
  return normalizedUploads;
}

// File Upload Service Integration (single file helper)
export async function UploadFile(params: UploadFileParams): Promise<UploadFileResponse> {
  const results = await UploadPhotos({
    files: [params.file],
    folder: params.folder,
    isPublic: params.isPublic,
    projectId: params.projectId,
    dailyUpdateId: params.dailyUpdateId,
  });

  const first = results[0];
  if (!first) {
    throw new Error('File upload failed – no metadata returned');
  }

  return {
    ...first,
    success: true,
    filename: first.fileName,
    type: first.mimeType,
  };
}

// Optional: SMS/Text Message Integration
export async function SendSMS(smsData: SMSData): Promise<SMSResponse> {
  const { to, message } = smsData;
  
  console.log('%c[API CALL] SendSMS()', 'color: #4CAF50; font-weight: bold');
  console.log('  → HTTP: POST /api/integrations/sms/send');
  console.log('  → SMS details:', {
    to,
    messageLength: message?.length || 0
  });
  console.log('  → Expected backend action:');
  console.log('    1. Validate phone number format');
  console.log('    2. Send via Twilio/AWS SNS/etc');
  console.log('    3. Handle delivery status');
  
  const mockResponse = {
    success: true,
    messageId: `sms-${Date.now()}`,
    to,
    status: 'queued',
  };
  
  console.log('  ← SMS "sent"');
  console.warn('  ⚠️  WARNING: This is a MOCK - no actual SMS was sent!');
  
  return mockResponse;
}

// Optional: Webhook/Notification Integration
export async function SendWebhook(webhookData: WebhookData): Promise<WebhookResponse> {
  const { url, event, payload } = webhookData;
  
  console.log('%c[API CALL] SendWebhook()', 'color: #673AB7; font-weight: bold');
  console.log('  → HTTP: POST /api/integrations/webhook');
  console.log('  → Webhook details:', {
    targetUrl: url,
    event,
    payloadSize: JSON.stringify(payload).length
  });
  console.log('  → Expected backend action:');
  console.log('    1. Validate webhook URL');
  console.log('    2. POST to external service');
  console.log('    3. Retry on failure');
  console.log('    4. Log webhook delivery');
  
  console.warn('  ⚠️  WARNING: This is a MOCK - no webhook was sent!');
  
  return { success: true, deliveredAt: new Date().toISOString() };
}
